### ISSUE TITLE
Should this show video previews for .webm?

### ISSUE THREAD

**Issue by DSBloom** [MiahNelah/audio-preview#2]
I know the name of the module is AUDIO Preview but it says it supports .webm. Should video previews be working in the file browser? 

Below is a screenshot of me trying to add an animated .webm tile.

![image](https://user-images.githubusercontent.com/5799503/132581086-25d3393c-a00c-4ae7-9fd3-f6217469f2dd.png)

**Comment by MiahNelah** [comment]
Hello! !That's a good question. WEBM file can be an audio file only, I admit I didn't test myself with this format since all API I used in this module leverage native Foundry's audio playback : I stated it's good. In all case, you may have audio preview but no video preview : this module don't support this at all.
